### ISSUE TITLE
AttributeError: 'Sequential' object has no attribute 'constraints'

### ISSUE THREAD

**Issue by nes123** [oarriaga/STN.keras#5]
this is due to loconet.constraints

**Comment by kritiagg** [comment]
any updates on this issue?

**Comment by hubermops** [comment]
Had the same problem. Tried commenting it out but didn't help. Looks like it doesn't work with the current Keras version. Anybody else had more luck?

**Comment by mahdaneh** [comment]
had the same issue, downgrading my keras to keras=2.0 resolved the issue. 
pip install keras==2.0
