### ISSUE TITLE
projective transformation 

### ISSUE THREAD

**Issue by betterze** [oarriaga/STN.keras#9]
Dear Oarriaga,

Your implement of STN is awesome, thx a lot for doing this.

In STN.keras/src/models/STN.py, line 23-24

     locnet = Dense(6, weights=weights)(locnet)
     x = BilinearInterpolation(sampling_size)([image, locnet])

the locnet is set to have 6 parameter, which means affine transformation, but I want to do projective transformation, which require 9 (actually 8) parameters, could I just change 6 to 9, or I need to rewrite the whole BilinearInterpolation function? 

The BilinearInterpolation function is a little bit long, it may take me some time to fully understand it. 

Thank you very much for your help.

Best Wishes,

Alex

**Comment by oarriaga** [comment]
You would need to adapt some aspects of the BilinearInterpolation layer; mostly, the application of the matrix transformation to the grid.
